export type ReportComponentCategory = 'text' | 'structure' | 'data' | 'indicators' | 'charts' | 'document';

export interface ReportComponentSnippet {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: ReportComponentCategory;
  files: Array<'HTML' | 'CSS' | 'JS' | 'JSON'>;
  html: string;
  css?: string;
  javascript?: string;
  data?: Record<string, unknown>;
}

export const REPORT_COMPONENT_CATEGORIES: ReadonlyArray<{value: 'all' | ReportComponentCategory; label: string; icon: string}> = [
  {value: 'all', label: 'Todos', icon: 'pi pi-th-large'}, {value: 'text', label: 'Texto', icon: 'pi pi-align-left'}, {value: 'structure', label: 'Estrutura', icon: 'pi pi-box'},
  {value: 'data', label: 'Dados', icon: 'pi pi-database'}, {value: 'indicators', label: 'Indicadores', icon: 'pi pi-chart-line'}, {value: 'charts', label: 'Gráficos', icon: 'pi pi-chart-bar'},
  {value: 'document', label: 'Documento', icon: 'pi pi-file'}
];

function formatHtml(source: string): string {
  const tokens = source.trim().replace(/>\s*</g, '><').split(/(?=<)|(?<=>)/).map(token => token.trim()).filter(Boolean);
  let level = 0;
  return tokens.map(token => {
    if (token.startsWith('</')) level = Math.max(0, level - 1);
    const line = `${'  '.repeat(level)}${token}`;
    if (token.startsWith('<') && !token.startsWith('</') && !token.startsWith('<!') && !token.startsWith('<?') && !token.endsWith('/>') && !/^<[^>]+>[^<]+<\//.test(token)) level++;
    return line;
  }).join('\n');
}

function formatCss(source: string): string {
  return source.trim().replace(/}\s*/g, '}\n').replace(/\{\s*/g, ' {\n  ').replace(/;\s*/g, ';\n  ').replace(/\n  }/g, '\n}').trim();
}

const component = (item: ReportComponentSnippet): ReportComponentSnippet => ({
  ...item,
  html: `\n<!-- sr:component:${item.id} -->\n${formatHtml(item.html)}\n`,
  css: item.css ? `\n/* sr:component:${item.id} */\n${formatCss(item.css)}\n` : undefined,
  javascript: item.javascript ? `\n// sr:component:${item.id}\n${item.javascript.trim()}\n` : undefined
});

export const REPORT_COMPONENTS: readonly ReportComponentSnippet[] = [
  component({id:'text-field', name:'Campo de texto', description:'Rótulo e valor dinâmico', icon:'pi pi-align-left', category:'text', files:['HTML','CSS','JSON'], html:`<div class="sr-field"><span class="sr-field__label">Cliente</span><strong>{{ data.customerName }}</strong></div>`, css:`.sr-field{display:grid;gap:4px}.sr-field__label{color:#64748b;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}`, data:{customerName:'Empresa Exemplo Ltda.'}}),
  component({id:'title-block', name:'Título de seção', description:'Título com texto de apoio', icon:'pi pi-align-center', category:'text', files:['HTML','CSS'], html:`<header class="sr-title"><span>{{ data.title.eyebrow }}</span><h2>{{ data.title.heading }}</h2><p>{{ data.title.description }}</p></header>`, css:`.sr-title{margin:0 0 18px}.sr-title span{color:#0f766e;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.sr-title h2{margin:5px 0 4px;color:#0f172a;font-size:22px}.sr-title p{margin:0;color:#64748b;font-size:12px}`, data:{title:{eyebrow:'Visão geral',heading:'Resultados do período',description:'Principais informações consolidadas para análise.'}}}),
  component({id:'status-badge', name:'Status', description:'Selo de situação do registro', icon:'pi pi-tag', category:'text', files:['HTML','CSS','JSON'], html:`<span class="sr-badge" :class="'sr-badge--' + data.status.type">{{ data.status.label }}</span>`, css:`.sr-badge{display:inline-flex;padding:5px 10px;border-radius:999px;background:#dcfce7;color:#166534;font-size:10px;font-weight:800}.sr-badge--warning{background:#fef3c7;color:#92400e}.sr-badge--danger{background:#fee2e2;color:#991b1b}`, data:{status:{label:'Aprovado',type:'success'}}}),
  component({id:'divider', name:'Divisor', description:'Separador com legenda opcional', icon:'pi pi-minus', category:'structure', files:['HTML','CSS'], html:`<div class="sr-divider"><span>Detalhamento</span></div>`, css:`.sr-divider{display:flex;align-items:center;gap:10px;margin:18px 0;color:#64748b;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.09em}.sr-divider:after{content:"";height:1px;flex:1;background:#e2e8f0}`}),
  component({id:'two-columns', name:'Duas colunas', description:'Grade responsiva para conteúdo', icon:'pi pi-th-large', category:'structure', files:['HTML','CSS'], html:`<div class="sr-grid-2"><section><h3>{{ data.columns.first.title }}</h3><p>{{ data.columns.first.content }}</p></section><section><h3>{{ data.columns.second.title }}</h3><p>{{ data.columns.second.content }}</p></section></div>`, css:`.sr-grid-2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}@media(max-width:600px){.sr-grid-2{grid-template-columns:1fr}}.sr-grid-2 section{padding:14px;border:1px solid #e2e8f0;border-radius:9px}.sr-grid-2 h3,.sr-grid-2 p{margin:0}.sr-grid-2 p{margin-top:5px;color:#64748b;font-size:10px}` , data:{columns:{first:{title:'Coluna 1',content:'Conteúdo da primeira coluna.'},second:{title:'Coluna 2',content:'Conteúdo da segunda coluna.'}}}}),
  component({id:'card', name:'Card', description:'Container destacado com cabeçalho', icon:'pi pi-stop', category:'structure', files:['HTML','CSS'], html:`<section class="sr-card"><header><h3>{{ data.card.title }}</h3><span>{{ data.card.updatedAt }}</span></header><p>{{ data.card.content }}</p></section>`, css:`.sr-card{padding:18px;background:#fff;border:1px solid #e2e8f0;border-radius:12px;box-shadow:0 5px 18px rgba(15,23,42,.06)}.sr-card header{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.sr-card h3,.sr-card p{margin:0}.sr-card header span{color:#94a3b8;font-size:9px}`, data:{card:{title:'Resumo',updatedAt:'Atualizado agora',content:'Insira aqui o conteúdo principal do card.'}}}),
  component({id:'callout', name:'Aviso', description:'Caixa para observação importante', icon:'pi pi-info-circle', category:'structure', files:['HTML','CSS'], html:`<aside class="sr-callout"><i>i</i><div><strong>{{ data.callout.title }}</strong><p>{{ data.callout.message }}</p></div></aside>`, css:`.sr-callout{display:flex;gap:12px;padding:14px 16px;background:#ecfeff;border:1px solid #a5f3fc;border-radius:10px;color:#155e75}.sr-callout>i{width:22px;height:22px;display:grid;place-items:center;background:#0891b2;color:#fff;border-radius:50%;font:700 12px serif}.sr-callout p{margin:3px 0 0;font-size:11px}`, data:{callout:{title:'Observação importante',message:'Adicione uma orientação relevante para quem receber o relatório.'}}}),
  component({id:'page-break', name:'Quebra de página', description:'Inicia o conteúdo na próxima página', icon:'pi pi-clone', category:'structure', files:['HTML','CSS'], html:`<div class="sr-page-break" aria-hidden="true"></div>`, css:`.sr-page-break{break-after:page;page-break-after:always}`}),
  component({id:'data-table', name:'Tabela', description:'Tabela completa com linhas dinâmicas', icon:'pi pi-table', category:'data', files:['HTML','CSS','JSON'], html:`<table class="sr-table"><thead><tr><th>Descrição</th><th>Categoria</th><th class="number">Valor</th></tr></thead><tbody><tr v-for="item in data.items" :key="item.description"><td>{{ item.description }}</td><td>{{ item.category }}</td><td class="number">{{ item.value }}</td></tr></tbody></table>`, css:`.sr-table{width:100%;border-collapse:separate;border-spacing:0;font-size:11px}.sr-table th{padding:10px 12px;background:#0f766e;color:#fff;text-align:left}.sr-table th:first-child{border-radius:7px 0 0}.sr-table th:last-child{border-radius:0 7px 0 0}.sr-table td{padding:10px 12px;border-bottom:1px solid #e2e8f0}.sr-table tbody tr:nth-child(even){background:#f8fafc}.sr-table .number{text-align:right;font-variant-numeric:tabular-nums}`, data:{items:[{description:'Licença SmartReport',category:'Software',value:'R$ 149,90'},{description:'Implantação',category:'Serviço',value:'R$ 350,00'}]}}),
  component({id:'key-value', name:'Detalhes', description:'Lista compacta de propriedades', icon:'pi pi-list', category:'data', files:['HTML','CSS','JSON'], html:`<dl class="sr-details"><template v-for="detail in data.details" :key="detail.label"><div><dt>{{ detail.label }}</dt><dd>{{ detail.value }}</dd></div></template></dl>`, css:`.sr-details{margin:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0;border:1px solid #e2e8f0;border-radius:10px;overflow:hidden}.sr-details div{padding:11px 14px;border-bottom:1px solid #e2e8f0}.sr-details dt{color:#64748b;font-size:9px;font-weight:700;text-transform:uppercase}.sr-details dd{margin:4px 0 0;color:#0f172a;font-size:12px;font-weight:700}`, data:{details:[{label:'Documento',value:'SR-2026-001'},{label:'Emissão',value:'24/07/2026'},{label:'Responsável',value:'Equipe SmartVerse'},{label:'Unidade',value:'Matriz'}]}}),
  component({id:'totals', name:'Totais', description:'Subtotal, desconto e total final', icon:'pi pi-calculator', category:'data', files:['HTML','CSS','JSON'], html:`<div class="sr-totals"><div><span>Subtotal</span><strong>{{ data.totals.subtotal }}</strong></div><div><span>Desconto</span><strong>{{ data.totals.discount }}</strong></div><div class="total"><span>Total</span><strong>{{ data.totals.total }}</strong></div></div>`, css:`.sr-totals{width:min(320px,100%);margin-left:auto;display:grid;gap:8px}.sr-totals div{display:flex;justify-content:space-between;padding:0 4px;color:#64748b;font-size:11px}.sr-totals .total{margin-top:3px;padding:12px 14px;background:#0f766e;color:#fff;border-radius:9px;font-size:14px}`, data:{totals:{subtotal:'R$ 499,90',discount:'R$ 49,99',total:'R$ 449,91'}}}),
  component({id:'kpi', name:'Indicador KPI', description:'Número de destaque com variação', icon:'pi pi-chart-line', category:'indicators', files:['HTML','CSS','JSON'], html:`<article class="sr-kpi"><div class="sr-kpi__icon">↗</div><span>Receita total</span><strong>{{ data.kpi.value }}</strong><small :class="{negative: data.kpi.variation < 0}">{{ data.kpi.variation }}% no período</small></article>`, css:`.sr-kpi{padding:17px;position:relative;background:linear-gradient(145deg,#fff,#f0fdfa);border:1px solid #ccfbf1;border-radius:12px}.sr-kpi__icon{position:absolute;right:14px;top:14px;width:28px;height:28px;display:grid;place-items:center;background:#ccfbf1;color:#0f766e;border-radius:8px}.sr-kpi>span{color:#64748b;font-size:10px}.sr-kpi>strong{display:block;margin:8px 0 5px;color:#0f172a;font-size:24px}.sr-kpi>small{color:#15803d;font-weight:700}.sr-kpi>small.negative{color:#dc2626}`, data:{kpi:{value:'R$ 84.320',variation:12.8}}}),
  component({id:'progress', name:'Progresso', description:'Meta com percentual alcançado', icon:'pi pi-percentage', category:'indicators', files:['HTML','CSS','JSON'], html:`<div class="sr-progress"><header><span>{{ data.progress.label }}</span><strong>{{ data.progress.value }}%</strong></header><div class="sr-progress__track"><i :style="{width: data.progress.value + '%'}"></i></div><small>{{ data.progress.caption }}</small></div>`, css:`.sr-progress header{display:flex;justify-content:space-between;margin-bottom:7px;font-size:11px}.sr-progress__track{height:8px;overflow:hidden;background:#e2e8f0;border-radius:999px}.sr-progress__track i{display:block;height:100%;background:linear-gradient(90deg,#0f766e,#06b6d4);border-radius:inherit}.sr-progress small{display:block;margin-top:5px;color:#64748b;font-size:9px}`, data:{progress:{label:'Meta mensal',value:72,caption:'R$ 72 mil de R$ 100 mil'}}}),
  component({id:'bar-chart', name:'Gráfico de barras', description:'Comparativo vertical sem dependências', icon:'pi pi-chart-bar', category:'charts', files:['HTML','CSS','JSON'], html:`<figure class="sr-chart"><figcaption>Vendas por mês</figcaption><div class="sr-bars"><div v-for="point in data.barChart" :key="point.label" class="sr-bar"><span>{{ point.value }}</span><i :style="{height: point.percent + '%'}"></i><small>{{ point.label }}</small></div></div></figure>`, css:`.sr-chart{margin:0;padding:18px;border:1px solid #e2e8f0;border-radius:12px}.sr-chart figcaption{margin-bottom:16px;font-size:13px;font-weight:800}.sr-bars{height:170px;display:flex;align-items:flex-end;gap:12px;border-bottom:1px solid #cbd5e1}.sr-bar{height:100%;flex:1;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:5px}.sr-bar i{width:min(36px,70%);min-height:3px;background:linear-gradient(#06b6d4,#0f766e);border-radius:6px 6px 0 0}.sr-bar span,.sr-bar small{font-size:8px;color:#64748b}`, data:{barChart:[{label:'Jan',value:'42k',percent:42},{label:'Fev',value:'68k',percent:68},{label:'Mar',value:'55k',percent:55},{label:'Abr',value:'86k',percent:86}]}}),
  component({id:'line-chart', name:'Gráfico de linha', description:'Evolução em SVG adaptável', icon:'pi pi-chart-line', category:'charts', files:['HTML','CSS'], html:`<figure class="sr-line-chart"><figcaption>{{ data.lineChart.title }}</figcaption><svg viewBox="0 0 500 170" role="img" aria-label="Gráfico de evolução"><defs><linearGradient id="srLineFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#14b8a6" stop-opacity=".28"/><stop offset="1" stop-color="#14b8a6" stop-opacity="0"/></linearGradient></defs><polyline :points="data.lineChart.points.map(point => point.x + ',' + point.y).join(' ')"/><g><circle v-for="point in data.lineChart.points" :key="point.label" :cx="point.x" :cy="point.y" r="4"/></g></svg><div class="sr-line-labels"><span v-for="point in data.lineChart.points" :key="point.label">{{ point.label }}</span></div></figure>`, css:`.sr-line-chart{margin:0;padding:18px;border:1px solid #e2e8f0;border-radius:12px}.sr-line-chart figcaption{font-size:13px;font-weight:800}.sr-line-chart svg{width:100%;margin-top:10px;overflow:visible}.sr-line-labels{display:flex;justify-content:space-between;color:#64748b;font-size:8px}.sr-line-chart polyline{fill:none;stroke:#0f766e;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.sr-line-chart .area{fill:url(#srLineFill)}.sr-line-chart circle{fill:#fff;stroke:#0f766e;stroke-width:3}`, data:{lineChart:{title:'Evolução do período',points:[{label:'Jan',x:10,y:140},{label:'Fev',x:90,y:110},{label:'Mar',x:170,y:122},{label:'Abr',x:250,y:66},{label:'Mai',x:330,y:82},{label:'Jun',x:410,y:34},{label:'Jul',x:490,y:48}]}}}),
  component({id:'pie-chart', name:'Gráfico de pizza', description:'Distribuição percentual em donut', icon:'pi pi-chart-pie', category:'charts', files:['HTML','CSS','JSON'], html:`<figure class="sr-donut-card"><div class="sr-donut" :style="{'--a': data.pieChart[0].value + '%','--b': (data.pieChart[0].value + data.pieChart[1].value) + '%'}"><span><strong>100%</strong><small>Total</small></span></div><figcaption><div v-for="(slice,index) in data.pieChart" :key="slice.label"><i :class="'c' + index"></i><span>{{ slice.label }}</span><strong>{{ slice.value }}%</strong></div></figcaption></figure>`, css:`.sr-donut-card{margin:0;padding:18px;display:flex;align-items:center;justify-content:center;gap:25px;border:1px solid #e2e8f0;border-radius:12px}.sr-donut{width:130px;height:130px;display:grid;place-items:center;border-radius:50%;background:conic-gradient(#0f766e 0 var(--a),#06b6d4 var(--a) var(--b),#f59e0b var(--b) 100%)}.sr-donut:before{content:"";width:76px;height:76px;position:absolute;background:#fff;border-radius:50%}.sr-donut span{z-index:1;display:grid;text-align:center}.sr-donut small{color:#64748b;font-size:8px}.sr-donut-card figcaption{min-width:130px;display:grid;gap:10px}.sr-donut-card figcaption div{display:grid;grid-template-columns:8px 1fr auto;align-items:center;gap:7px;font-size:10px}.sr-donut-card figcaption i{width:8px;height:8px;background:#0f766e;border-radius:2px}.sr-donut-card .c1{background:#06b6d4}.sr-donut-card .c2{background:#f59e0b}`, data:{pieChart:[{label:'Produto',value:48},{label:'Serviços',value:32},{label:'Outros',value:20}]}}),
  component({id:'document-header', name:'Cabeçalho', description:'Marca, título e identificação', icon:'pi pi-id-card', category:'document', files:['HTML','CSS','JSON'], html:`<header class="sr-document-header"><div class="sr-brand"><span>SR</span><div><strong>{{ data.company.name }}</strong><small>{{ data.company.subtitle }}</small></div></div><div class="sr-document-meta"><strong>RELATÓRIO</strong><span>{{ data.documentNumber }}</span></div></header>`, css:`.sr-document-header{display:flex;align-items:center;justify-content:space-between;padding-bottom:16px;border-bottom:2px solid #0f766e}.sr-brand{display:flex;align-items:center;gap:10px}.sr-brand>span{width:38px;height:38px;display:grid;place-items:center;background:linear-gradient(145deg,#0f766e,#0891b2);color:#fff;border-radius:9px;font-weight:900}.sr-brand div,.sr-document-meta{display:grid;gap:2px}.sr-brand small,.sr-document-meta span{color:#64748b;font-size:9px}.sr-document-meta{text-align:right;color:#0f766e}`, data:{company:{name:'SmartVerse',subtitle:'Relatórios inteligentes'},documentNumber:'#2026-001'}}),
  component({id:'signature', name:'Assinaturas', description:'Campos formais para assinatura', icon:'pi pi-pencil', category:'document', files:['HTML','CSS'], html:`<section class="sr-signatures"><div><span></span><strong>{{ data.signatures.responsible }}</strong><small>{{ data.signatures.responsibleHint }}</small></div><div><span></span><strong>{{ data.signatures.customer }}</strong><small>{{ data.signatures.customerHint }}</small></div></section>`, css:`.sr-signatures{margin-top:54px;display:grid;grid-template-columns:repeat(2,1fr);gap:48px;text-align:center}.sr-signatures span{display:block;border-top:1px solid #64748b}.sr-signatures strong{display:block;margin-top:7px;font-size:10px}.sr-signatures small{color:#94a3b8;font-size:8px}`, data:{signatures:{responsible:'Responsável',responsibleHint:'Nome e assinatura',customer:'Cliente',customerHint:'Nome e assinatura'}}}),
  component({id:'receipt-items', name:'Itens de comprovante', description:'Lista compacta para bobina térmica', icon:'pi pi-receipt', category:'document', files:['HTML','CSS','JSON'], html:`<section class="sr-receipt-items"><div v-for="item in data.receiptItems" :key="item.name"><span>{{ item.quantity }}x {{ item.name }}</span><strong>{{ item.total }}</strong><small>{{ item.unit }} cada</small></div></section>`, css:`.sr-receipt-items{display:grid;border-top:1px dashed #64748b}.sr-receipt-items div{padding:8px 0;display:grid;grid-template-columns:1fr auto;border-bottom:1px dashed #cbd5e1;font-size:10px}.sr-receipt-items strong{text-align:right}.sr-receipt-items small{color:#64748b;font-size:8px}`, data:{receiptItems:[{quantity:2,name:'Produto exemplo',unit:'R$ 12,50',total:'R$ 25,00'},{quantity:1,name:'Serviço adicional',unit:'R$ 30,00',total:'R$ 30,00'}]}}),
  component({id:'qr-placeholder', name:'QR Code', description:'Espaço visual para QR Code real', icon:'pi pi-qrcode', category:'document', files:['HTML','CSS'], html:`<div class="sr-qr"><div class="sr-qr__code" aria-label="Substitua pelo QR Code gerado"></div><div><strong>Escaneie para validar</strong><small>Substitua o quadro pela imagem do QR Code.</small></div></div>`, css:`.sr-qr{display:flex;align-items:center;justify-content:center;gap:12px;padding:14px}.sr-qr__code{width:58px;height:58px;border:7px solid #0f172a;background:repeating-conic-gradient(#0f172a 0 25%,#fff 0 50%) 50%/14px 14px}.sr-qr div:last-child{display:grid;gap:3px}.sr-qr small{max-width:150px;color:#64748b;font-size:8px}`})
  ,component({id:'customer-card', name:'Cartão do cliente', description:'Identificação completa do cliente', icon:'pi pi-user', category:'document', files:['HTML','CSS','JSON'], html:`<section class="sr-customer"><div class="sr-customer__avatar">{{ data.customer.initials }}</div><div><span>Cliente</span><strong>{{ data.customer.name }}</strong><small>{{ data.customer.document }} · {{ data.customer.email }}</small></div><span class="sr-customer__type">{{ data.customer.type }}</span></section>`, css:`.sr-customer{display:flex;align-items:center;gap:12px;padding:14px 16px;border:1px solid #dbeafe;background:#eff6ff;border-radius:12px}.sr-customer__avatar{width:38px;height:38px;display:grid;place-items:center;flex:0 0 auto;color:#fff;background:linear-gradient(145deg,#2563eb,#06b6d4);border-radius:50%;font-size:11px;font-weight:900}.sr-customer div:nth-child(2){min-width:0;display:grid;gap:2px}.sr-customer div:nth-child(2) span{color:#2563eb;font-size:9px;font-weight:800;text-transform:uppercase}.sr-customer strong{color:#0f172a;font-size:12px}.sr-customer small{overflow:hidden;color:#64748b;font-size:9px;text-overflow:ellipsis;white-space:nowrap}.sr-customer__type{margin-left:auto;padding:4px 8px;color:#1d4ed8;background:#dbeafe;border-radius:999px;font-size:8px;font-weight:800}`, data:{customer:{initials:'EE',name:'Empresa Exemplo Ltda.',document:'CNPJ 00.000.000/0001-00',email:'contato@exemplo.com',type:'Premium'}}})
  ,component({id:'timeline', name:'Linha do tempo', description:'Histórico de etapas e eventos', icon:'pi pi-history', category:'document', files:['HTML','CSS','JSON'], html:`<ol class="sr-timeline"><li v-for="event in data.timeline" :key="event.title" :class="{done: event.done}"><i></i><div><strong>{{ event.title }}</strong><small>{{ event.date }} · {{ event.description }}</small></div></li></ol>`, css:`.sr-timeline{margin:0;padding:3px 0;list-style:none;display:grid;gap:0}.sr-timeline li{position:relative;display:grid;grid-template-columns:22px 1fr;gap:10px;min-height:48px}.sr-timeline li:not(:last-child):before{content:"";position:absolute;left:7px;top:15px;bottom:0;width:2px;background:#e2e8f0}.sr-timeline li i{z-index:1;width:16px;height:16px;margin-top:2px;border:3px solid #cbd5e1;background:#fff;border-radius:50%}.sr-timeline li.done i{border-color:#0f766e;background:#14b8a6}.sr-timeline li div{display:grid;gap:3px}.sr-timeline strong{font-size:11px}.sr-timeline small{color:#64748b;font-size:9px}`, data:{timeline:[{title:'Pedido recebido',date:'24/07/2026 09:15',description:'Solicitação registrada',done:true},{title:'Em análise',date:'24/07/2026 10:40',description:'Validação dos dados',done:true},{title:'Concluído',date:'Previsão 25/07/2026',description:'Aguardando processamento',done:false}]}})
  ,component({id:'rating', name:'Avaliação', description:'Nota visual com estrelas', icon:'pi pi-star', category:'indicators', files:['HTML','CSS','JSON'], html:`<div class="sr-rating"><div><span>Experiência do cliente</span><strong>{{ data.rating.value }}/5</strong></div><div class="sr-rating__stars"><i v-for="star in 5" :key="star" :class="star <= data.rating.value ? 'filled' : ''">★</i></div><small>{{ data.rating.caption }}</small></div>`, css:`.sr-rating{padding:15px 17px;border:1px solid #fde68a;background:#fffbeb;border-radius:11px}.sr-rating>div:first-child{display:flex;justify-content:space-between;align-items:center}.sr-rating span{color:#92400e;font-size:10px;font-weight:700}.sr-rating strong{color:#78350f;font-size:14px}.sr-rating__stars{display:flex;gap:3px;margin:7px 0 3px}.sr-rating__stars i{color:#d1d5db;font-style:normal;font-size:17px}.sr-rating__stars i.filled{color:#f59e0b}.sr-rating small{color:#a16207;font-size:9px}`, data:{rating:{value:4,caption:'Muito bom — baseado em 128 avaliações'}}})
  ,component({id:'report-footer', name:'Rodapé do relatório', description:'Rodapé com contato e confidencialidade', icon:'pi pi-align-justify', category:'document', files:['HTML','CSS','JSON'], html:`<footer class="sr-footer"><span>{{ data.footer.company }} · {{ data.footer.contact }}</span><span>{{ data.footer.confidential }}</span></footer>`, css:`.sr-footer{margin-top:28px;padding-top:10px;display:flex;justify-content:space-between;gap:12px;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:8px}.sr-footer span:last-child{text-align:right}`, data:{footer:{company:'SmartVerse',contact:'contato@smartverse.com.br',confidential:'Documento confidencial'}}})
  ,component({id:'barcode', name:'Código de barras', description:'Identificador visual para impressão', icon:'pi pi-barcode', category:'document', files:['HTML','CSS','JSON'], html:`<div class="sr-barcode"><div class="sr-barcode__lines" aria-label="Código de barras"></div><span>{{ data.barcode }}</span></div>`, css:`.sr-barcode{display:grid;justify-items:center;gap:5px;padding:12px}.sr-barcode__lines{width:190px;height:42px;background:repeating-linear-gradient(90deg,#0f172a 0 2px,#fff 2px 4px,#0f172a 4px 5px,#fff 5px 8px)}.sr-barcode span{font:10px ui-monospace,monospace;letter-spacing:.16em;color:#0f172a}`, data:{barcode:'7891234567890'}})

];

export function appendSnippetOnce(source: string, snippet: string | undefined, marker: string): string {
  if (!snippet || source.includes(marker)) return source;
  return `${source.trimEnd()}${source.trim() ? '\n' : ''}${snippet}`;
}

export function mergeComponentData(source: string, patch?: Record<string, unknown>): string {
  if (!patch) return source;
  const current = source.trim() ? JSON.parse(source) : {};
  if (!current || Array.isArray(current) || typeof current !== 'object') throw new Error('O JSON precisa ter um objeto na raiz.');
  const merge = (target: Record<string, unknown>, addition: Record<string, unknown>) => {
    for (const [key, value] of Object.entries(addition)) {
      if (!(key in target)) target[key] = value;
      else if (value && typeof value === 'object' && !Array.isArray(value) && target[key] && typeof target[key] === 'object' && !Array.isArray(target[key])) merge(target[key] as Record<string, unknown>, value as Record<string, unknown>);
    }
  };
  merge(current as Record<string, unknown>, patch);
  return JSON.stringify(current, null, 2);
}
